# Generated by Django 6.0.2 on 2026-02-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('icao', models.CharField(max_length=4, unique=True)),
                ('iata', models.CharField(blank=True, max_length=3)),
                ('country', models.CharField(max_length=2)),
            ],
            options={
                'verbose_name': 'Airline',
                'verbose_name_plural': 'Airline',
            },
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('icao', models.CharField(max_length=4, primary_key=True, serialize=False, unique=True)),
                ('iata', models.CharField(blank=True, max_length=3)),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=2)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lon', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
            options={
                'ordering': ['icao'],
            },
        ),
    ]
