# Generated by Django 6.0.2 on 2026-02-25 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airline',
            name='id',
        ),
        migrations.AddField(
            model_name='airline',
            name='lock',
            field=models.CharField(default='X', max_length=1, primary_key=True, serialize=False),
        ),
    ]
