# Generated by Django 6.0.2 on 2026-03-04 15:37

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_airline_id_airline_lock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airline',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='airline',
            name='icao',
            field=models.CharField(max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='airport',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
