# Generated by Django 6.0.2 on 2026-03-04 15:37

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_myuser_country_myuser_curr_airport_myuser_rank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
