# Generated by Django 6.0.3 on 2026-03-08 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_myuser_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'ordering': ['-date_joined']},
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='last_name',
        ),
        migrations.AddField(
            model_name='myuser',
            name='full_name',
            field=models.CharField(blank=True, verbose_name='full name'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.CharField(unique=True, verbose_name='email address'),
        ),
    ]
