# Generated by Django 6.0.3 on 2026-03-08 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pireps', '0002_flight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='scheduled', max_length=20),
        ),
    ]
