# Generated by Django 6.0.2 on 2026-02-26 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_remove_airline_id_airline_lock'),
    ]

    operations = [
        migrations.CreateModel(
            name='FleetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('icao_code', models.CharField(max_length=6, unique=True)),
                ('pax_capacity', models.IntegerField()),
                ('cargo_capacity', models.IntegerField()),
                ('ci', models.IntegerField()),
            ],
            options={
                'ordering': ['icao_code'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('flight_time', models.DurationField()),
                ('is_active', models.BooleanField(default=True)),
                ('arrival_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='core.airport')),
                ('departure_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='core.airport')),
                ('fleet_allowed', models.ManyToManyField(to='operations.fleettype')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
    ]
