# Generated by Django 6.0.2 on 2026-02-26 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
                ('booked_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bid', to=settings.AUTH_USER_MODEL)),
                ('fleet_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.fleettype')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.route')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
