# Generated by Django 6.0.2 on 2026-02-26 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_bid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='booked_by',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='active_bid', to=settings.AUTH_USER_MODEL),
        ),
    ]
